import {
  blackfram,
  blackfram1,
  blackfram2,
  blackfram3,
  blackfram4,
  blackfram5,
  blackfram6,
  blackfram7,
  blackfram8,
  grayfram,
  grayfram1,
  grayfram2,
  grayfram3,
  grayfram4,
  grayfram5,
  grayfram6,
  grayfram7,
  grayfram8,
  whitefram,
  whitefram1,
  whitefram2,
  whitefram3,
  whitefram4,
  whitefram5,
  whitefram6,
} from "../../../assets/Allimages";

const DashboardFields = [
  {
    id: 1,
    whiteImg: whitefram,
    blackImg: blackfram,
    grayImg: grayfram,
    txtNm: "Personal information",
  },
  {
    id: 2,
    whiteImg: whitefram1,
    blackImg: blackfram1,
    grayImg: grayfram1,
    txtNm: "Education",
  },
  {
    id: 3,
    whiteImg: whitefram2,
    blackImg: blackfram2,
    grayImg: grayfram2,
    txtNm: "Internship",
  },
  {
    id: 4,
    whiteImg: whitefram3,
    blackImg: blackfram3,
    grayImg: grayfram3,
    txtNm: "Projects",
  },
  {
    id: 5,
    whiteImg: whitefram4,
    blackImg: blackfram4,
    grayImg: grayfram4,
    txtNm: "Skills",
  },
  {
    id: 6,
    whiteImg: whitefram5,
    blackImg: blackfram5,
    grayImg: grayfram5,
    txtNm: "Certification",
  },
  {
    id: 7,
    whiteImg: whitefram6,
    blackImg: blackfram6,
    grayImg: grayfram6,
    txtNm: "Achievements",
  },
  {
    id: 8,
    whiteImg: whitefram6,
    blackImg: blackfram7,
    grayImg: grayfram7,
    txtNm: "Hobbies",
  },
  {
    id: 9,
    whiteImg: grayfram8,
    blackImg: blackfram8,
    grayImg: grayfram8,
    txtNm: "Languages",
  },
];

export default DashboardFields;
